replicaCount: 1

image:
  tag: "dev-3c339a5"
  # opcional, si quieres sobrescribir repository o pullPolicy:
  # repository: emi8977/medchek-app-code
  # pullPolicy: IfNotPresent

ingress:
  enabled: true
  hosts:
    - host: dev.medchek.local
      paths:
        - path: /
          pathType: Prefix

