nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: emi8977/medchek-app-code
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: medchek.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
